appname: student-tracker-app

namespace: my-app

secret:
  name: vault-secrets
  VAULT_ADDR: "http://44.204.193.107:8200"
  VAULT_ROLE_ID: "f7af58b1-5c22-7c2d-c659-0425d9ce94b2"
  VAULT_SECRET_ID: "d5f736da-785b-8f5c-9258-48d5d7c43c06"

service:
  name: my-app-service
  protocol: TCP
  port: 80
  targetPort: 8000
  type: NodePort

app:
  name: my-app
  replicas: 2
  containerPort: 8000

image:
  repository: keneojiteli/student-tracker
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  name: my-app-ingress
  className: nginx
  host: ec2-18-232-214-103.compute-1.amazonaws.com
  path: /
  pathType: Prefix
